clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          # Deploy to Digital Ocean
          - mkdir -p ~/.ssh
          - cat my_known_hosts >> ~/.ssh/known_hosts
          - (umask 077; echo $SSH_PRIVATE_KEY | base64 --decode -i > ~/.ssh/id_rsa)
          - git remote add server $DOCEAN_GIT_REPO
          - git push server master
